# Generated by Django 2.2.2 on 2019-06-24 23:44

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_updated", models.DateTimeField()),
                ("name", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to=app.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name="GradingJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("backup_id", models.CharField(max_length=10)),
                ("access_token", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (app.models.JobStatusEnum("QUEUED"), "QUEUED"),
                            (app.models.JobStatusEnum("FINISHED"), "FINISHED"),
                            (app.models.JobStatusEnum("RUNNING"), "RUNNING"),
                        ],
                        max_length=10,
                    ),
                ),
                ("enqueued_time", models.DateTimeField()),
                ("dequeue_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.Assignment",
                    ),
                ),
            ],
        ),
    ]
