# Generated by Django 2.2.2 on 2019-06-24 23:46

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="gradingjob",
            name="dequeue_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="enqueued_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="finish_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="status",
            field=models.CharField(
                choices=[
                    (app.models.JobStatusEnum("QUEUED"), "QUEUED"),
                    (app.models.JobStatusEnum("FINISHED"), "FINISHED"),
                    (app.models.JobStatusEnum("RUNNING"), "RUNNING"),
                ],
                default=app.models.JobStatusEnum("QUEUED"),
                max_length=10,
            ),
        ),
    ]
