# Generated by Django 2.2.2 on 2019-06-25 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("app", "0002_auto_20190624_2346")]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docker_image", models.CharField(max_length=50)),
                ("parallelism", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Use thie field as okpy's autograder_key",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
